name: flutter_error_privserver_example
description: Example app demonstrating flutter_error_privserver usage
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  cubit_ui_flow:
    git: 
      url: git@github.com:qtpi-bonding-org/flutter_cubit_ui_flow.git
      ref: 737f24b
  flutter_error_privserver:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true